version: "3.8"

x-file-path: &file-path ./../../config/services.yaml

services:
  portainer:
    extends:
      file: *file-path
      service: portainer
    networks:
      - admin

  portainer_agent:
    extends:
      file: *file-path
      service: portainer_agent
    networks:
      - admin

  mysql:
    extends:
      file: *file-path
      service: mysql
    networks:
      - admin

  phpmyadmin:
    extends:
      file: *file-path
      service: phpmyadmin
    networks:
      - admin

  redis:
    extends:
      file: *file-path
      service: redis
    networks:
      - admin

  redis-commander:
    extends:
      file: *file-path
      service: redis-commander
    networks:
      - admin

  postgres:
    extends:
      file: *file-path
      service: postgres
    networks:
      - admin

  pgadmin:
    extends:
      file: *file-path
      service: pgadmin
    networks:
      - admin

networks:
  admin:
    driver: bridge
