version: "3.8"

x-file-path: &file-path ./../../config/services.yaml

services:
  jenkins:
    extends:
      file: *file-path
      service: jenkins
    networks:
      - admin

networks:
  admin:
    driver: bridge

volumes:
  jenkins_home:
    driver: local
