version: "3.8"

x-file-path: &file-path ./../../config/services.yaml

services:
  portainer:
    extends:
      file: *file-path
      service: portainer
    networks:
      - admin
    volumes:
      - ./data/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock

  yacht:
    extends:
      file: *file-path
      service: yacht
    networks:
      - admin
    volumes:
      - ./data/yacht:/config
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  admin:
    driver: bridge
