version: "3.8"

x-file-path: &file-path ./../../config/services.yaml

services:
  rabbitmq:
    extends:
      file: *file-path
      service: rabbitmq
    networks:
      - infra
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq

  mongo:
    extends:
      file: *file-path
      service: mongo
    networks:
      - infra

  influx:
    extends:
      file: *file-path
      service: influx
    networks:
      - infra

volumes:
  rabbitmq-data:
networks:
  infra:
    driver: bridge
