version: "3.8"

services:
  rabbitmq:
    extends:
      file: ../../configs/services.yaml
      service: rabbitmq
    networks:
      - backend
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq

  mongo:
    extends:
      file: ../../configs/services.yaml
      service: mongo
    networks:
      - backend

volumes:
  rabbitmq-data:
networks:
  backend:
    driver: bridge
