version: "3.8"

services:
  rabbitmq:
    extends:
      file: ../../configs/services.yaml
      service: rabbitmq
    networks:
      - backend
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq

  mongo:
    extends:
      file: ../../configs/services.yaml
      service: mongo
    networks:
      - backend

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"  # Jaeger UI port
      - "6831:6831/udp"  # Jaeger compact Thrift port
      - "6832:6832/udp"  # Jaeger binary Thrift port
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411

volumes:
  rabbitmq-data:
networks:
  backend:
    driver: bridge
