version: "3.8"

x-file-path: &file-path ./../../config/services.yaml

services:
  sqlserver:
    extends:
      file: *file-path
      service: sqlserver
    networks:
      - infra

volumes:
  rabbitmq-data:
networks:
  infra:
    driver: bridge
