version: "3.8"

x-file-path: &file-path /../../config/services.yaml

services:
  rabbitmq:
    extends:
      file: *file-path
      service: rabbitmq
    networks:
      - backend
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq

  mongo:
    extends:
      file: *file-path
      service: mongo
    networks:
      - backend

volumes:
  rabbitmq-data:
networks:
  backend:
    driver: bridge
